pipeline:
  build:
    image: vespakoen/ssh-rsync
    volumes:
      - /root/.vagrant.d/insecure_private_key:/vagrant_key
    commands:
      - export SSH_COMMAND="ssh -o Compression=yes -o DSAAuthentication=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -i /vagrant_key"
      - rsync -q -avrc --delete --exclude "/node_modules" -e "$SSH_COMMAND" . vagrant@192.168.33.10:/Users/vagrant/devconnect
      - eval "$SSH_COMMAND vagrant@192.168.33.10 /Users/vagrant/devconnect/ci.sh"
      - rsync -q -avrc -e "$SSH_COMMAND" vagrant@192.168.33.10:/Users/vagrant/devconnect/dist/* ./dist
  release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: ./dist
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
    when:
      event: tag
  notify:
    image: plugins/slack
    channel: dev
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]